# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rubyschool

# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Курсы по Ruby и Rails

# baseurl: > ""
url: https://github.com/de956.github.io # the base hostname & protocol for your site
# baseurl: 

include: ['_pages']

copyright:
  name: rubyschool

# Build settings
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

